### ISSUE TITLE
Calendar is not applying colors when selecting dates

### ISSUE THREAD

**Issue by mferreiradb** [elreco/vue-tailwind-datepicker#128]
When trying to determine a start date and an end date, the calendar fills the two selected days with white and does not apply a background to the days that fall between the end date and the start date. In the print, I selected the 13th on the calendar on the left and the 17th on the calendar on the right.

![print-calendar](https://github.com/elreco/vue-tailwind-datepicker/assets/99357847/0a961af5-194b-4975-85b9-57fa4da3d18c)

Unfortunately I cannot make the repository available, as it is from an application of the company where I work.

**Comment by cedric-nxstar** [comment]
I just ran into this problem. It seems to happen when you use "colors.black" as the primary color in your tailwind.config.{js|ts}:
```
const colors = require("tailwindcss/colors")

export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/vue-tailwind-datepicker/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        "vtd-primary": colors.black, // Light mode Datepicker color
        "vtd-secondary": colors.white, // Dark mode Datepicker color
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
```

I reckon this happens because "black" can not be declined in "-50", "-100", "-200", ... versions.

It would be really great to be able to manually choose which color to apply to different parts of the picker, instead of being trapped with automatic variations of 2 colors.
