### ISSUE TITLE
Could not find a declaration file for module 'vue-tailwind-datepicker'.

### ISSUE THREAD

**Issue by gedeondoescode** [elreco/vue-tailwind-datepicker#17]
v1.1.1 has affected how the package is imported under a ts script tag. Types are no longer available to import. 

![Screenshot_20221106_125248](https://user-images.githubusercontent.com/75461444/200186890-b985f5d9-61d0-404d-9c99-1298e9430462.png)

**After reinstalling all packages**
![Screenshot_20221106_125544](https://user-images.githubusercontent.com/75461444/200186988-614b219d-bd70-4aa7-bb3e-52f431242311.png)

**package updated to the latest version**
![Screenshot_20221106_125721](https://user-images.githubusercontent.com/75461444/200187021-c375183f-653e-49ee-830f-e816872cae6a.png)

I've already attempted to reinstall the package, delete the node_modules folder and ran ``npm ci`` but nothing's changed.

**Comment by elreco** [comment]
@gedeondoescode It should works now with the v1.1.2, can you tell me if it's ok for you pls?

**Comment by gedeondoescode** [comment]
@elreco it works perfectly now! Thank you!

**Comment by erick661** [comment]
This problem is back in 1.4.4

No se encontró ningún archivo de declaración para el módulo 'vue-tailwind-datepicker'. '/Users/erick/Sites/estadisticas/est-vue-ts-tw/node_modules/vue-tailwind-datepicker/dist/vue-tailwind-datepicker.mjs' tiene un tipo "any" de forma implícita.
  There are types at '/Users/erick/Sites/estadisticas/est-vue-ts-tw/node_modules/vue-tailwind-datepicker/dist/types.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-tailwind-datepicker' library may need to update its package.json or typings.

 "vue": "^3.2.47",
    "vue-router": "^4.2.1",
    "vue-tailwind-datepicker": "^1.4.4",
