### ISSUE TITLE
Css problem

### ISSUE THREAD

**Issue by minhchau2605** [elreco/vue-tailwind-datepicker#33]
why is my css like this, how can i fix it ?
![image](https://user-images.githubusercontent.com/27195377/205479691-b438be84-e417-4ede-b1b6-b356d394b606.png)

**Comment by elreco** [comment]
hello @minhchau2605 did you install tailwind on your project? Or do you have another framework/css file which is generating a conflict

**Comment by chipit24** [comment]
I ran into this issue as well. For me it was due to overriding the `screens` config in my Tailwind config. I added `tablet`, `laptop` and `desktop` keys instead of keeping the default `sm`, `md`, `lg`, etc. which `vue-tailwind-datepicker` uses.

If Tailwind weren't installed, or if it were installed but not configured correctly with `"./node_modules/vue-tailwind-datepicker/**/*.js"` listed under `content`, then the datepicker would either not render, or render much differently than in the screenshot posted, so I believe @minhchau2605 has a similar problem to mine.

You can read about customizing the screens in the Tailwind docs at https://tailwindcss.com/docs/screens. It looks like the datepicker only uses `sm` and `lg` breakpoints, so I added `sm: "640px", lg: "640px"` to my `screens` config to match my `tablet` screen size and that made things look good for me.
